from django.db import models
from django.utils.functional import cached_property


class RowVersionField(models.BinaryField):
    """
    SQL Server `rowversion`/`timestamp` columns are generated by the engine.
    Mark the field as generated so Django excludes it from INSERT/UPDATE.
    """

    generated = True
    db_returning = False

    @cached_property
    def referenced_fields(self):
        return frozenset()
