from django.db import models


class RowVersionField(models.BinaryField):
    """
    SQL Server `rowversion`/`timestamp` columns are generated by the engine.
    Mark the field as generated so Django excludes it from INSERT/UPDATE.
    """

    generated = True

