from django.urls import path

from apps.informes.views.web import module_page

urlpatterns = [
    path('', module_page(template_name='informes/informe_list.html', page_title='Informes', page_description='Consulta el listado de informes generados o en proceso.', page_actions=[], page_highlights=[{'label': 'Modulo', 'value': 'Informes'}, {'label': 'Pantalla', 'value': 'Informes'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Consulta el listado de informes generados o en proceso.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='informes-lista'),
    path('generar/', module_page(template_name='informes/informe_generate.html', page_title='Generar informe', page_description='Prepara la construccion del informe de autoevaluacion.', page_actions=[{'label': 'Informes', 'url_name': 'informes-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Informes'}, {'label': 'Pantalla', 'value': 'Generar informe'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Prepara la construccion del informe de autoevaluacion.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='informes-generar'),
    path('detalle/', module_page(template_name='informes/informe_detail.html', page_title='Detalle de informe', page_description='Visualiza relacion con documento, ciclo y estado del informe.', page_actions=[{'label': 'Informes', 'url_name': 'informes-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Informes'}, {'label': 'Pantalla', 'value': 'Detalle de informe'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Visualiza relacion con documento, ciclo y estado del informe.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='informes-detalle'),
    path('aprobar/', module_page(template_name='informes/informe_approve.html', page_title='Aprobar informe', page_description='Gestiona el cambio de estado y validacion del informe.', page_actions=[{'label': 'Informes', 'url_name': 'informes-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Informes'}, {'label': 'Pantalla', 'value': 'Aprobar informe'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Gestiona el cambio de estado y validacion del informe.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='informes-aprobar'),
]
