# Generated by Django 5.2.10 on 2026-01-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activacion',
            fields=[
                ('id_activacion', models.AutoField(db_column='id_activacion', primary_key=True, serialize=False)),
                ('descripcion_activacion', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'activacion',
            },
        ),
        migrations.CreateModel(
            name='CicloEvaluacion',
            fields=[
                ('id_ciclo', models.AutoField(db_column='id_ciclo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_in', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'ciclo_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id_criterio', models.AutoField(db_column='id_criterio', primary_key=True, serialize=False)),
                ('nombre_criterio', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'criterio',
            },
        ),
        migrations.CreateModel(
            name='EstadoAsignacion',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'estado_asignacion',
            },
        ),
        migrations.CreateModel(
            name='EstadoIndicador',
            fields=[
                ('id_estado_ind', models.AutoField(db_column='id_estado_ind', primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'estado_indicador',
            },
        ),
        migrations.CreateModel(
            name='EstadoMejora',
            fields=[
                ('id_estado_mejora', models.AutoField(db_column='id_estado_mejora', primary_key=True, serialize=False)),
                ('descipcion_estado_mejora', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'estado_mejora',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(db_column='id_evaluacion', primary_key=True, serialize=False)),
                ('calificacion_cuantitativa', models.IntegerField()),
                ('calificacion_cualitativa', models.IntegerField()),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(db_column='id_indicador', primary_key=True, serialize=False)),
                ('nombre_indicador', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'indicador',
            },
        ),
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id_tipo_ind', models.AutoField(db_column='id_tipo_ind', primary_key=True, serialize=False)),
                ('descripcion_tipo_ind', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'tipo_indicador',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(db_column='id_auditoria', primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=150)),
                ('tabla_afectada', models.CharField(max_length=150)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('valores_nuevos', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_anteriores', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_evento', models.DateTimeField()),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'auditoria',
            },
        ),
        migrations.CreateModel(
            name='CicloActivacion',
            fields=[
                ('id_ciclo_act', models.AutoField(db_column='id_ciclo_act', primary_key=True, serialize=False)),
                ('activacion', models.ForeignKey(db_column='id_activacion', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_activacion', to='core.activacion')),
                ('ciclo', models.ForeignKey(db_column='id_ciclo', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_activacion', to='core.cicloevaluacion')),
                ('indicador', models.ForeignKey(db_column='id_indicador', on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_activacion', to='core.indicador')),
            ],
            options={
                'db_table': 'ciclo_activacion',
            },
        ),
        migrations.CreateModel(
            name='Pedi',
            fields=[
                ('id_pedi', models.AutoField(db_column='id_pedi', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateTimeField()),
                ('ciclo_activacion', models.ForeignKey(db_column='id_ciclo_act', on_delete=django.db.models.deletion.PROTECT, related_name='pedis', to='core.cicloactivacion')),
            ],
            options={
                'db_table': 'pedi',
            },
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id_plan_accion', models.AutoField(db_column='id_plan_accion', primary_key=True, serialize=False)),
                ('objetivo_estrategicos', models.IntegerField()),
                ('descripcion_objetivos_estrategicos', models.CharField(max_length=500)),
                ('pedi', models.ForeignKey(db_column='id_pedi', on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='core.pedi')),
            ],
            options={
                'db_table': 'plan_accion',
            },
        ),
        migrations.CreateModel(
            name='PlanMejora',
            fields=[
                ('id_plan_mejora', models.AutoField(db_column='id_plan_mejora', primary_key=True, serialize=False)),
                ('estandar', models.CharField(max_length=150)),
                ('linea_base', models.CharField(max_length=250)),
                ('meta', models.CharField(max_length=250)),
                ('aspectos_mejora', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medios_verificacion', models.CharField(max_length=500)),
                ('evaluacion', models.ForeignKey(db_column='id_evaluacion', on_delete=django.db.models.deletion.PROTECT, related_name='planes_mejora', to='core.evaluacion')),
                ('plan_accion', models.ForeignKey(db_column='id_plan_accion', on_delete=django.db.models.deletion.PROTECT, related_name='planes_mejora', to='core.planaccion')),
            ],
            options={
                'db_table': 'plan_mejora',
            },
        ),
        migrations.CreateModel(
            name='PlanMejoraActividad',
            fields=[
                ('id_plan_actividad', models.AutoField(db_column='id_plan_actividad', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('avance', models.IntegerField()),
                ('estado_mejora', models.ForeignKey(db_column='id_estado_mejora', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.estadomejora')),
                ('plan_mejora', models.ForeignKey(db_column='id_plan_mejora', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='core.planmejora')),
            ],
            options={
                'db_table': 'plan_mejora_actividad',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsignacion',
            fields=[
                ('id_registro_asignacion', models.AutoField(db_column='id_registro_asignacion', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_maxima', models.DateTimeField()),
                ('argumentacion', models.CharField(max_length=500)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('ciclo_activacion', models.ForeignKey(db_column='id_ciclo_act', on_delete=django.db.models.deletion.PROTECT, related_name='registros_asignacion', to='core.cicloactivacion')),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='registros_asignacion', to='core.estadoasignacion')),
                ('estado_indicador', models.ForeignKey(db_column='id_estado_ind', on_delete=django.db.models.deletion.PROTECT, related_name='registros_asignacion', to='core.estadoindicador')),
            ],
            options={
                'db_table': 'registro_asignacion',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificaciones', models.AutoField(db_column='id_notificaciones', primary_key=True, serialize=False)),
                ('detalle_notificiacion', models.CharField(max_length=500)),
                ('registro_asignacion', models.ForeignKey(db_column='id_registro_asignacion', on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='core.registroasignacion')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='registro_asignacion',
            field=models.ForeignKey(db_column='id_registro_asignacion', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='core.registroasignacion'),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.AutoField(db_column='id_responsable', primary_key=True, serialize=False)),
                ('descripcion_responsabilidad', models.CharField(max_length=500)),
                ('usuario_rol', models.ForeignKey(db_column='id_user_rol', on_delete=django.db.models.deletion.PROTECT, related_name='responsabilidades', to='seguridad.usuariorol')),
            ],
            options={
                'db_table': 'responsable',
            },
        ),
        migrations.AddField(
            model_name='registroasignacion',
            name='responsable',
            field=models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='registros_asignacion', to='core.responsable'),
        ),
        migrations.AddField(
            model_name='planmejora',
            name='responsable',
            field=models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.PROTECT, related_name='planes_mejora', to='core.responsable'),
        ),
        migrations.CreateModel(
            name='Subcriterio',
            fields=[
                ('id_subcriterio', models.AutoField(db_column='id_subcriterio', primary_key=True, serialize=False)),
                ('nombre_subcriterio', models.CharField(max_length=150)),
                ('criterio', models.ForeignKey(db_column='id_criterio', on_delete=django.db.models.deletion.PROTECT, related_name='subcriterios', to='core.criterio')),
            ],
            options={
                'db_table': 'subcriterio',
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='subcriterio',
            field=models.ForeignKey(db_column='id_subcriterio', on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='core.subcriterio'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipo_ind',
            field=models.ForeignKey(db_column='id_tipo_ind', on_delete=django.db.models.deletion.PROTECT, related_name='indicadores', to='core.tipoindicador'),
        ),
    ]
