from django.urls import path

from apps.evaluacion.views.web import module_page

urlpatterns = [
    path('evidencias/registrar/', module_page(template_name='evaluacion/evidencia_form.html', page_title='Registrar evidencia', page_description='Registra evidencia enlazada a documento, elemento, indicador y ciclo.', page_actions=[], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Registrar evidencia'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Registra evidencia enlazada a documento, elemento, indicador y ciclo.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-evidencia-registrar'),
    path('evidencias/', module_page(template_name='evaluacion/evidencia_list.html', page_title='Lista de evidencias', page_description='Consulta las evidencias registradas para seguimiento y evaluacion.', page_actions=[{'label': 'Registrar evidencia', 'url_name': 'evaluacion-evidencia-registrar', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Lista de evidencias'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Consulta las evidencias registradas para seguimiento y evaluacion.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-evidencias-lista'),
    path('evidencias/detalle/', module_page(template_name='evaluacion/evidencia_detail.html', page_title='Detalle de evidencia', page_description='Revisa informacion, documento base y estado de evaluacion.', page_actions=[{'label': 'Registrar evidencia', 'url_name': 'evaluacion-evidencia-registrar', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Detalle de evidencia'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Revisa informacion, documento base y estado de evaluacion.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-evidencia-detalle'),
    path('bandeja/', module_page(template_name='evaluacion/bandeja_evaluacion.html', page_title='Bandeja de evaluacion', page_description='Centraliza las evidencias pendientes y en revision.', page_actions=[{'label': 'Registrar evidencia', 'url_name': 'evaluacion-evidencia-registrar', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Bandeja de evaluacion'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Centraliza las evidencias pendientes y en revision.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-bandeja'),
    path('evaluar/', module_page(template_name='evaluacion/evaluacion_form.html', page_title='Evaluar evidencia', page_description='Registra la evaluacion formal y su resultado.', page_actions=[{'label': 'Registrar evidencia', 'url_name': 'evaluacion-evidencia-registrar', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Evaluar evidencia'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Registra la evaluacion formal y su resultado.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-evaluar'),
    path('observaciones/', module_page(template_name='evaluacion/observacion_form.html', page_title='Observaciones', page_description='Gestiona observaciones derivadas de la evaluacion de evidencias.', page_actions=[{'label': 'Registrar evidencia', 'url_name': 'evaluacion-evidencia-registrar', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Evaluacion'}, {'label': 'Pantalla', 'value': 'Observaciones'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Gestiona observaciones derivadas de la evaluacion de evidencias.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='evaluacion-observaciones'),
]
