from django.urls import path

from apps.documentos.views.web import (
    AuthorizationCycleView,
    DocumentUploadView,
    ProtectedDocumentAccessView,
    ProtectedDocumentDownloadView,
    ProtectedDocumentGraphRedirectView,
    ProtectedDocumentPreviewView,
    module_page,
)

urlpatterns = [
    path('clasificaciones/', module_page(template_name='documentos/clasificacion_documento_list.html', page_title='Clasificaciones documentales', page_description='Administra categorias documentales para el repositorio protegido.', page_actions=[], page_highlights=[{'label': 'Modulo', 'value': 'Documentos'}, {'label': 'Pantalla', 'value': 'Clasificaciones documentales'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Administra categorias documentales para el repositorio protegido.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='documentos-clasificaciones-lista'),
    path('', module_page(template_name='documentos/documento_list.html', page_title='Documentos', page_description='Consulta el inventario documental del sistema y su estado.', page_actions=[{'label': 'Clasificaciones documentales', 'url_name': 'documentos-clasificaciones-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Documentos'}, {'label': 'Pantalla', 'value': 'Documentos'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Consulta el inventario documental del sistema y su estado.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='documentos-lista'),
    path('subir/', DocumentUploadView.as_view(), name='documentos-subir'),
    path('detalle/', module_page(template_name='documentos/documento_detail.html', page_title='Detalle de documento', page_description='Visualiza metadata documental, estructura y trazabilidad.', page_actions=[{'label': 'Clasificaciones documentales', 'url_name': 'documentos-clasificaciones-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Documentos'}, {'label': 'Pantalla', 'value': 'Detalle de documento'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Visualiza metadata documental, estructura y trazabilidad.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='documentos-detalle'),
    path('versiones/', module_page(template_name='documentos/version_documento_list.html', page_title='Historial de versiones', page_description='Consulta el versionamiento real de cada documento.', page_actions=[{'label': 'Clasificaciones documentales', 'url_name': 'documentos-clasificaciones-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Documentos'}, {'label': 'Pantalla', 'value': 'Historial de versiones'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Consulta el versionamiento real de cada documento.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='documentos-versiones'),
    path('accesos/', module_page(template_name='documentos/documento_acceso_log.html', page_title='Historial de accesos', page_description='Revisa la trazabilidad de acceso a documentos protegidos.', page_actions=[{'label': 'Clasificaciones documentales', 'url_name': 'documentos-clasificaciones-lista', 'variant': 'secondary'}], page_highlights=[{'label': 'Modulo', 'value': 'Documentos'}, {'label': 'Pantalla', 'value': 'Historial de accesos'}, {'label': 'Estado', 'value': 'Base administrativa'}], page_sections=[{'title': 'Objetivo', 'description': 'Revisa la trazabilidad de acceso a documentos protegidos.', 'items': ['Estructura visual preparada para administracion.', 'Ruta y pestaña integradas al panel.', 'Lista para conectar formularios, selectors y servicios.']}, {'title': 'Siguiente integracion', 'description': 'Pasos naturales para conectar la funcionalidad real.', 'items': ['Conectar selector de lectura.', 'Agregar formulario o tabla operativa.', 'Registrar eventos en auditoria si corresponde.']}]), name='documentos-accesos'),
    path('protegidos/<int:documento_id>/abrir/', ProtectedDocumentAccessView.as_view(), name='documentos-protegidos-abrir'),
    path('protegidos/<int:documento_id>/descargar/', ProtectedDocumentDownloadView.as_view(), name='documentos-protegidos-descargar'),
    path('protegidos/<int:documento_id>/preview/', ProtectedDocumentPreviewView.as_view(), name='documentos-protegidos-preview'),
    path('protegidos/<int:documento_id>/graph/', ProtectedDocumentGraphRedirectView.as_view(), name='documentos-protegidos-graph'),
    path('autorizacion-ciclo/', AuthorizationCycleView.as_view(), name='documentos-autorizacion-ciclo'),
]
