# Generated by Django 5.2.10 on 2026-01-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(db_column='id_documento', primary_key=True, serialize=False)),
                ('descipcion_documento', models.CharField(max_length=500)),
                ('graph_site_id', models.CharField(max_length=200)),
                ('graph_drive_id', models.CharField(max_length=200)),
                ('graph_item_id', models.CharField(max_length=200)),
                ('graph_web_url', models.CharField(max_length=500)),
                ('graph_etag', models.CharField(max_length=200)),
                ('graph_ctag', models.CharField(max_length=200)),
                ('graph_last_modified', models.DateTimeField()),
                ('graph_size', models.BigIntegerField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='EstadoEvidencia',
            fields=[
                ('id_estado_evidencia', models.AutoField(db_column='id_estado_evidencia', primary_key=True, serialize=False)),
                ('descripcion_estado_evidencia', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'estado_evidencia',
            },
        ),
        migrations.CreateModel(
            name='PlanMejoraDoc',
            fields=[
                ('id_doc_plan_m', models.AutoField(db_column='id_doc_plan_m', primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.PROTECT, related_name='planes_mejora', to='evidencias.documento')),
                ('plan_actividad', models.ForeignKey(db_column='id_plan_actividad', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.planmejoraactividad')),
            ],
            options={
                'db_table': 'plan_mejora_doc',
            },
        ),
        migrations.CreateModel(
            name='RegistroDocumento',
            fields=[
                ('id_registro_documento', models.AutoField(db_column='id_registro_documento', primary_key=True, serialize=False)),
                ('documento', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='evidencias.documento')),
                ('estado_evidencia', models.ForeignKey(db_column='id_estado_evidencia', on_delete=django.db.models.deletion.PROTECT, related_name='registros_documento', to='evidencias.estadoevidencia')),
                ('registro_asignacion', models.ForeignKey(db_column='id_registro_asignacion', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.registroasignacion')),
            ],
            options={
                'db_table': 'registro_documento',
            },
        ),
    ]
