# Generated by Django 5.2.10 on 2026-01-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('codigo_permiso', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('modulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipo_identificacion', models.AutoField(db_column='id_tipo_identificacion', primary_key=True, serialize=False)),
                ('descripcion_tp_identificacion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipo_identifiacion',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tp_user', models.AutoField(db_column='id_tp_user', primary_key=True, serialize=False)),
                ('descripcion_tp_user', models.CharField(max_length=150)),
                ('activo_tp_user', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(max_length=150)),
                ('primer_apellido', models.CharField(max_length=150)),
                ('segundo_apellido', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=15)),
                ('tipo_identificacion', models.ForeignKey(db_column='id_tipo_identificacion', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='seguridad.tipoidentificacion')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_usuario', models.ForeignKey(db_column='id_tp_user', on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='seguridad.tipousuario')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCredencial',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credencial', serialize=False, to='seguridad.usuario')),
                ('password_hash', models.BinaryField(max_length=255)),
                ('algortimo_hash', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField()),
                ('requiere_cambio', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usario_credenccial',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id_sesion', models.AutoField(db_column='id_sesion', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_renovacion', models.DateTimeField()),
                ('ip', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id_user_act', models.AutoField(db_column='id_user_act', primary_key=True, serialize=False)),
                ('login_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=45)),
                ('user_agent', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'user_activity',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.permiso')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='seguridad.rol')),
            ],
            options={
                'db_table': 'rol_permiso',
                'constraints': [models.UniqueConstraint(fields=('rol', 'permiso'), name='rol_permiso_pk')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_user_rol', models.AutoField(db_column='id_user_rol', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
                ('asignado_por', models.ForeignKey(blank=True, db_column='asignado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles_otorgados', to='seguridad.usuario')),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='seguridad.rol')),
                ('usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='roles_asignados', to='seguridad.usuario')),
            ],
            options={
                'db_table': 'usuario_rol',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='usuario_rol_uq')],
            },
        ),
    ]
